openapi: '3.0.2'

info:
  title: Users events
  version: 1.0.0

paths: {}

components:
  schemas:
    UserCreated:
      x-amazon-events-source: serverless-ecommerce.users
      x-amazon-events-detail-type: UserCreated
      description: Event emitted when a new user is created.
      allOf:
        - $ref: '../../shared/resources/schema.yml#EventBridgeHeader'
        - type: object
          properties:
            details:
              $ref: '../../shared/resources/schema.yml#User'
