# https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
name: Build and Install
description: Build and install NPM dependencies

inputs:
  node-version:
    description: The node version to setup
    required: false
    default: lts/fermium

runs:
  using: "composite"

  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

#    - name: Get yarn cache directory
#      id: yarn-cache-dir-path
#      shell: bash
#      run: echo "::set-output name=dir::$(yarn cache dir)"

#    - uses: actions/cache@v2
#      id: yarn
#      with:
#        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      shell: bash
#      if: steps.yarn.outputs.cache-hit != 'true'
      run: >-
        yarn install
        --frozen-lockfile
        --ignore-optional
        --ignore-platform
        --ignore-engines
        --emoji false
        --silent
        --no-progress
        --no-node-version-check
