EventBridgeHeader:
  type: object
  description: Headers for EventBridge schema definitions.
  properties:
    version:
      type: string
    id:
      type: string
      format: uuid
    account:
      type: string
      pattern: '^[0-9]{12}$'
    time:
      type: string
      format: date-time
    source:
      type: string
    detail-type:
      type: string
    resources:
      type: array
      items:
        type: string

User:
  type: object
  description: Representation of a single user.
  required:
    - userId
  properties:
    userId:
      type: string
      format: uuid
      description: Unique identifier in UUID format for the user.
      example: b2d0c356-f92b-4629-a87f-786331c2842f
    email:
      type: string
      format: email
      description: User email address, used to log in the user.
      example: john.doe@example.com
