name: audit

on:
  # Triggers the workflow on push
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: lts/fermium
  CI: true

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build-and-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run security check
        run: yarn audit --level=4

      - name: Run linting check
        run: echo "check ..."

  services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [users]
    defaults:
      run:
        working-directory: services

    steps:
      - uses: actions/checkout@v2

      - name: Checkout service
        run:  cd ${{ matrix.services }}

      - uses: ./.github/actions/build-and-install
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run security check
        run: yarn audit --level=4

      - name: Run linting check
        run: echo "check ..."
