name: audit

on:
  # Triggers the workflow on push
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: lts/fermium
  CI: true

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --no-progress --silent

      - name: Run security check
        run: yarn audit --level=4

      - name: Run linting check
        run: echo "check ..."

  services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [users]
    defaults:
      run:
        working-directory: services/${{ matrix.services }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --no-progress --silent

      - name: Run security check
        continue-on-error: true
        run: yarn audit --level=4

      - name: Run linting check
        run: echo "check ..."
