name: tests

on:
  workflow_run:
    workflows: ['audit']
    types: ['completed']

env:
  NODE_VERSION: lts/fermium
  CI: true

jobs:
  infra:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --no-progress --silent

      - name: Run tests
        run: yarn test

  services:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        services: [users]
    defaults:
      run:
        working-directory: services/${{ matrix.services }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --no-progress --silent

      - name: Run tests
        run: yarn test
